PYTORCH INTRO

In [3]:
import torch

In [4]:
z = torch.zeros(5,3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


- we created a 2 dimensional tensor with 5 rows and 3 columns filled with zeros
- we check the datatype to see that the default is 32bit floating point numbers

In [5]:
i = torch.ones((5,3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


- you can specify the datatype on creation

In [11]:
torch.manual_seed(1729) # Value for PRNG which ensures reproducibility of results
r1 = torch.rand(2,2) # initialize random learning weights
print("A random tensor: ")
print(r1)

r2 = torch.rand(2,2)
print("\n A different random tensor")
print(r2) # New Values

torch.manual_seed(1729)
r3 = torch.rand(2,2)
print("\nShould match r1")
print(r3) # repeats values of r1 because of reseed

A random tensor: 
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

 A different random tensor
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


In [12]:
ones = torch.ones(2,3)
print(ones)

twos = torch.ones(2,3)*2 # every element is multiplied by 2
print(twos)

threes = ones + twos

print(threes)
print(threes.shape) #has the same dimensions as input tensors
r1 = torch.rand(2,3)
r2 = torch.rand(3,2)
r3 = r1+r2

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1